[tool.pylint.'MESSAGES CONTROL']
disable = [
    "too-few-public-methods",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.darkrag]
debug_mode = false
chunk_size = 1000
chunk_overlap = 100
